### ISSUE TITLE
Can't pass unit tests

### ISSUE THREAD

**Issue by Gregor14** [mu-editor/mu#2207]
### What were you trying to do?

This is my fist time here, so: Hi to everyone,. I'm trying to pass unit test in Developer Setup

### What steps did you take to trigger the issue?

I intend to preprare my work place to create new mode in Mu Editor.

My enviroment:
- zip downloaded from https://github.com/mu-editor/mu
- Windows 10  21H1
- Python 3.8 (also checked at 3.8.10). No other installation of Python.
- PyQt5 5.13.2
- latest Mu 1.1.1

Now, I can run Mu (i.e. through mu-editor) from my virtualenv. I can run python code inside MuEditor. 
If I comment out code checking (by remove `if check() != 0:raise RuntimeError("Check failed")`) I can build Win64 installer.
But I can't pass tests. I's seems, there is problem with encoding cp1250. Therefore I check in Python: `import sys; print(sys.stdin.encoding, sys.stdout.encoding)` I get: `utf-8 utf-8`

### What did you expect to happen?

Pass all tests

### What actually happened?

I made each unit test separately. Here what I get:

make clean 
OK

make black
```
Traceback (most recent call last):
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Grzegorz\AppData\Local\Programs\mu-master\my_virt\lib\site-packages\black\__main__.py", line 3, in <module>
    patched_main()
  File "C:\Users\Grzegorz\AppData\Local\Programs\mu-master\my_virt\lib\site-packages\black\__init__.py", line 1372, in patched_main
    patch_click()
  File "C:\Users\Grzegorz\AppData\Local\Programs\mu-master\my_virt\lib\site-packages\black\__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (C:\Users\Grzegorz\AppData\Local\Programs\mu-master\my_virt\lib\site-packages\click\__init__.py)
```

make flake8
....... hundred of similar lines like this:
```
.\my_virt\Scripts\rst2s5.py:15:1: E722 do not use bare 'except'
.\my_virt\Scripts\rst2xetex.py:14:1: E722 do not use bare 'except'
.\my_virt\Scripts\rst2xml.py:14:1: E722 do not use bare 'except'
.\my_virt\Scripts\rstpep2html.py:15:1: E722 do not use bare 'except'
```

make coverage
```
_____________________________________________ test_read_encoding_default ______________________________________________

    def test_read_encoding_default():
        """Successfully decode from the default locale"""
>       test_string = UNICODE_TEST_STRING.encode(locale.getpreferredencoding())

tests\test_logic.py:3053:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.cp1250.Codec object at 0x0000023FE5AF83D0>
input = ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f\xa0¡¢£¤¥¦§¨©ª«¬\xad®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþ'
errors = 'strict'

    def encode(self,input,errors='strict'):
>       return codecs.charmap_encode(input,errors,encoding_table)
E       UnicodeEncodeError: 'charmap' codec can't encode characters in position 97-99: character maps to <undefined>

..\Python\Python38\lib\encodings\cp1250.py:12: UnicodeEncodeError

----------- coverage: platform win32, python 3.8.0-final-0 -----------
Name                         Stmts   Miss  Cover   Missing
----------------------------------------------------------
mu\__init__.py                   7      0   100%
mu\app.py                      161      1    99%   198
mu\config.py                     8      0   100%
mu\debugger\client.py          200      0   100%
mu\debugger\config.py            1      0   100%
mu\debugger\runner.py          254      0   100%
mu\debugger\utils.py            11      0   100%
mu\i18n.py                       8      1    88%   22
mu\interface\__init__.py         2      0   100%
mu\interface\dialogs.py        353     14    96%   368-369, 681-685, 691-692, 699-707
mu\interface\editor.py         278      0   100%
mu\interface\main.py           664      7    99%   773, 825-826, 838, 897, 941, 984
mu\interface\panes.py          949      7    99%   617, 1126, 1496-1497, 1503-1505
mu\interface\themes.py         201      0   100%
mu\interface\widgets.py         80      0   100%
mu\logic.py                    848      7    99%   898, 937-939, 1119-1123
mu\modes\__init__.py            12      0   100%
mu\modes\api\__init__.py        12      0   100%
mu\modes\api\adafruit.py         1      0   100%
mu\modes\api\esp.py              1      0   100%
mu\modes\api\flask.py            1      0   100%
mu\modes\api\lego.py             1      0   100%
mu\modes\api\microbit.py         1      0   100%
mu\modes\api\pi.py               1      0   100%
mu\modes\api\pyboard.py          1      0   100%
mu\modes\api\pygamezero.py       1      0   100%
mu\modes\api\python3.py          1      0   100%
mu\modes\api\shared.py           1      0   100%
mu\modes\api\snek.py             1      0   100%
mu\modes\base.py               342      0   100%
mu\modes\circuitpython.py       85     11    87%   208-213, 287-308
mu\modes\debugger.py           181      0   100%
mu\modes\esp.py                105      0   100%
mu\modes\lego.py                14      0   100%
mu\modes\microbit.py           313     17    95%   78-90, 335-344, 373-377, 390-397
mu\modes\pico.py                14      0   100%
mu\modes\pyboard.py             58      0   100%
mu\modes\pygamezero.py          64      0   100%
mu\modes\python3.py            179     10    94%   42-58
mu\modes\snek.py               187     71    62%   44-53, 59-77, 80-91, 97-98, 103-105, 108-127, 130-139, 144-156, 161
mu\modes\web.py                107      0   100%
mu\resources\__init__.py        26      0   100%
mu\settings.py                 124      0   100%
mu\virtual_environment.py      352     19    95%   199, 202, 205, 252-257, 440, 492, 495, 706-716
----------------------------------------------------------
TOTAL                         6211    165    97%

=============================================== short test summary info ===============================================
FAILED tests/test_logic.py::test_read_encoding_default - UnicodeEncodeError: 'charmap' codec can't encode characters ...
```

### Operating System Version

Win10 21H1

### Mu Version

1.1.1

### Other Info

I will appreciate for any clue, to find problem.

**Comment by Gregor14** [comment]
OK, I made some additional tests.
1. Is possible to rid of errors from `make coverage`, when I change in Win (advance keyboard settings) to use for unknown programs cp1250 or utf-8. 
2. Tests on Windows was made either in regular console (cmd.exe) and in powershell as well. Result is same.
3. According to manual for developers, I did same test on Ubuntu 20.04LTS. Still I got errors on `make black` and `make flake8` . I didn't any changes, just plain source from git and test made in venv.
4. Is possible to reduce errors from `black`. I remove limitation in setup.py, then I made update to 22.3.0. Now, result is:
```
All done! ✨ 🍰 ✨
1 file would be left unchanged.
would reformat make.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```
Better, but still fail. It stop at make.py. I run this: `black make.py --check -v --diff`. `Black` present me few places to change, i.e.
```
-        raise RuntimeError(
-            "Cannot run Mu;" "your Python virtualenv is not activated"
-        )
+        raise RuntimeError("Cannot run Mu;" "your Python virtualenv is not activated")
     return subprocess.run([sys.executable, "-m", "mu"]).returncode
```
Seems, he don't like multi-line commands :) Maybe this is caused by this "inappropriate" `black 22.3.0`, or something else. Due to my lack of experience in this environment, I can't tell.

Summarize: still I can't pass `make black` and `make flake8`

According to recommendations from Mu manual, I'm really trying to solve this problem of tests. However, I get impression that I did some fundamental error, but I don't see it. 

Could anybody confirm me, that is really possible to pass whole `make check` without errors?
Thanks, Gregor

**Comment by carlosperate** [comment]
If you've updated to the latest commits in the main branch (from a few minutes ago) that should have fixed the issues with click.

If you pip install `black==21.12b0` do you still get issues?

**Comment by Gregor14** [comment]
1. On previous post I made a mistake with claim: `black` `would reformat make.py`  This was not an issue in Mu but in me :) I opened make.py in Pycharm, made Code/Reformat Code and in few places in file, was added (by Pycharm) spaces before commands. `black` don't like it, and issue claims with `would reformat make.py` . Sorry for mess.
2. I just made fresh installations Mu code on Ubuntu and Win. In both, I use `black==21.12b0`  `click==8.0.4`
`black `on linux: now is OK
`black `on Win (cmd and ps): error `would reformat mu\contrib\uflash.py`
I compare uflash.py from Ubuntu and Win. There are identical (in fact, to make sure, I overwrite it from Ubuntu to Win)
`flake8`: still same problems.
`coverage`: OK
3. Before I use your, today, most fresh repo, with `black21.12b0` and `black22.1.0` I had problem like: `ImportError: cannot import name '_unicodefun' from 'click'`. Now with this new repo, I can work with regular `black==21.12b0`, thanks

**Comment by Gregor14** [comment]
I made some additional tests and I know why appears problems on Windows with `would reformat mu\contrib\uflash.py`  
In short:
`make black`  gives correct result
`python make.py black`  correct
`py make.py black`  gives `would reformat mu\contrib\uflash.py`
`make.py black`  gives `would reformat mu\contrib\uflash.py`

Summarise (now  I have same result on Win and Ubuntu):
`make black`  OK
`make flash8`   always gives me hundred of errors
`make coverage`  this is in some way "time depend test", so sometimes gives OK in some occasions make error in random positions.

So, there is difference in behaviour between command `py` and `python`. This was surprise for me (I'm new in Python), I have habit to use TAB key to complete commands, so previous time probably I made `make.py black` . Both Python commands (py and python) gives me:` Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32`
For this test I make completely new installation. Below you will find list of commands exactly, as I wrote it. So, there will be no mistake again at my side (like `make `and `make.py`)  :)
Decompress whole latest zip in c:\Users\Grzegorz\AppData\Local\Programs\mu-master4. Run `cmd.exe` in this very folder.
```
python -m venv my_virt
my_virt\Scripts\activate.bat
python -m pip install --upgrade pip
pip install -e ".[dev]"
mu-editor
make check
```
Last command stops at flake8. And that is my last (at this moment :) problem with whole test procedure
Below you will find result `pip list --verbose` (of course from my_virt)
```
Package                       Version     Editable project location                           Location                                                                      Installer
----------------------------- ----------- --------------------------------------------------- ----------------------------------------------------------------------------- ---------
adafruit-board-toolkit        1.1.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
alabaster                     0.7.12                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
appdirs                       1.4.4                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
asttokens                     2.0.5                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
atomicwrites                  1.4.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
attrs                         21.4.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
Babel                         2.10.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
backcall                      0.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
black                         21.12b0                                                         c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
bleach                        5.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
certifi                       2021.10.8                                                       c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
charset-normalizer            2.0.12                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
click                         8.0.4                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
colorama                      0.4.4                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
commonmark                    0.9.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
coverage                      6.3.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
decorator                     5.1.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
distlib                       0.3.4                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
docutils                      0.17.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
executing                     0.8.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
filelock                      3.7.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
flake8                        4.0.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
idna                          3.3                                                             c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
imagesize                     1.3.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
importlib-metadata            4.11.3                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
iniconfig                     1.1.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
ipykernel                     5.5.6                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
ipython                       8.3.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
ipython-genutils              0.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
jedi                          0.18.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
Jinja2                        3.1.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
jupyter-client                6.1.12                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
jupyter-core                  4.10.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
keyring                       23.5.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
MarkupSafe                    2.1.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
matplotlib-inline             0.1.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
mccabe                        0.6.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
mu-editor                     1.1.1       c:\users\grzegorz\appdata\local\programs\mu-master4 c:\users\grzegorz\appdata\local\programs\mu-master4
mypy-extensions               0.4.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
nudatus                       0.0.5                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
packaging                     21.3                                                            c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
parso                         0.8.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pathspec                      0.9.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pickleshare                   0.7.5                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pip                           22.1                                                            c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pkginfo                       1.8.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
platformdirs                  2.5.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pluggy                        1.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
prompt-toolkit                3.0.29                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pure-eval                     0.2.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
py                            1.11.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pycodestyle                   2.8.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pyflakes                      2.4.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
Pygments                      2.12.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pyparsing                     3.0.9                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
PyQt5                         5.13.2                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
PyQt5-sip                     12.10.1                                                         c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
PyQtChart                     5.13.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pyserial                      3.5                                                             c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytest                        7.1.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytest-cov                    3.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytest-faulthandler           2.0.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytest-random-order           1.0.4                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytest-timeout                2.1.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
python-dateutil               2.8.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pytz                          2022.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pywin32                       304                                                             c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pywin32-ctypes                0.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
pyzmq                         22.3.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
QScintilla                    2.11.3                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
qtconsole                     4.7.7                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
QtPy                          2.1.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
readme-renderer               35.0                                                            c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
requests                      2.27.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
requests-toolbelt             0.9.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
rfc3986                       2.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
rich                          12.4.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
semver                        2.13.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
setuptools                    41.2.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
six                           1.16.0                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
snowballstemmer               2.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
Sphinx                        4.5.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-applehelp       1.0.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-devhelp         1.0.2                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-htmlhelp        2.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-jsmath          1.0.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-qthelp          1.0.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
sphinxcontrib-serializinghtml 1.1.5                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
stack-data                    0.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
tomli                         1.2.3                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
tornado                       6.1                                                             c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
traitlets                     5.2.1.post0                                                     c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
twine                         4.0.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
typing_extensions             4.2.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
urllib3                       1.26.9                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
virtualenv                    20.14.1                                                         c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
wcwidth                       0.2.5                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
webencodings                  0.5.1                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
wheel                         0.37.1                                                          c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
zipp                          3.8.0                                                           c:\users\grzegorz\appdata\local\programs\mu-master4\my_virt\lib\site-packages pip
```

**Comment by carlosperate** [comment]
Hi @Gregor14,
I've tried this on Windows and I'm not encountering any of this issues.

Could you start from zero (from a new git clone) and try again?
If you can then copy and paste all the steps and most importantly, their output, I can see if that gives any indication of what might be happening.


So something like this (adapt as you need):
```
git clone https://github.com/mu-editor/mu.git
cd mu
python -m venv .venv
.venv\Scripts\activate.bat
pip install -e ".[dev]"
python -m make.py check
```

**Comment by carlosperate** [comment]
> BTW: command python -m make.py check won't work (see log below). With python make.py check I was able to do it.

Oh yeah, sorry, that was my mistake, glad you were able to figure out the `-m` wasn't meant to be there!

Also glad you were able to get it to work! 🎉 

I'll close this issue as resolved.
